import java.awt.Color;
import java.io.*;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class kelime_oyunu extends javax.swing.JFrame {

    /**
     * Creates new form kelime_oyunu
     */
    ArrayList<Integer> list = new ArrayList<Integer>();
    static int salise=0;
    static int saniye=0;
    static int dakika=4;
    static boolean durum=true;
    
    static int salise2=0;
    static int saniye2=20;
    static boolean durum2=true;
    
    public kelime_oyunu() {
        initComponents();
        Tarih();
        jButton3.setIcon(new ImageIcon(getClass().getResource("/resimler/indir.png")));
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jButton5.setVisible(false);
        jButton8.setVisible(false);
        jButton12.setVisible(false);
        jButton7.setVisible(false);
        
         veri=new String[ss];
         try
        {
            FileInputStream fStream=new FileInputStream("4Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri[rnd];
        dataArray=data.split("--");
        soru=dataArray[0];
        cevap=dataArray[1];
        //
        list.clear();
        for (int i=0; i<4; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);
        
    }     
    
    String[] dataArray = null;
    int rnd= (int) ((Math.random()*satirSayisi()));
    String ad="";
    String soru="",cevap="";
    int skor=0;
    int sayac=0;
    static int sorusayac=0;
    String str="";
    String data="";
    String []veri;
    int sorudegeri=400;
    int ss=satirSayisi();
 
    String[] dataArray2 = null;
    String []veri2;
    int ss2=satirSayisi2("5Harfliler.txt");
    
    String[] dataArray3 = null;
    String []veri3;
    int ss3=satirSayisi2("6Harfliler.txt");
    
     String[] dataArray4 = null;
    String []veri4;
    int ss4=satirSayisi2("7Harfliler.txt");
    
     String[] dataArray5 = null;
    String []veri5;
    int ss5=satirSayisi2("8Harfliler.txt");
    
     String[] dataArray6 = null;
    String []veri6;
    int ss6=satirSayisi2("9Harfliler.txt");
    
     String[] dataArray7 = null;
    String []veri7;
    int ss7=satirSayisi2("10Harfliler.txt");
    
    int rndsayac=-1;
    static int harfsayac=0;
    int dogru=0;
    int random=(int) (Math.random() * (cevap.length()));
    int [] rnddizi;
    int jokersayar=0;
    int jokersayar2=0;
    
    void Tarih()
    {
        Date d =new Date();
        SimpleDateFormat s= new SimpleDateFormat("dd-MM-yyyy");
        jLabel28.setText(s.format(d));
    }
    
    public static int satirSayisi(){
    int sayac=0;
    try
        {
            FileInputStream fStream=new FileInputStream("4Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            while(bReader.readLine()!=null) {
                sayac++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        return sayac;
}
    
    public static int satirSayisi2(String a){
    int sayac=0;
    try
        {
            FileInputStream fStream=new FileInputStream(a);
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            while(bReader.readLine()!=null) {
                sayac++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        return sayac;
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoşgeldiniz"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Oyuncu Adı");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BAŞLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton9.setText("Soru Ekleme");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(51, 0, 51));
        jButton10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Talimatlar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Skor"));

        jLabel18.setText("Oyuncu Adı:");

        jLabel20.setText("Skor:");

        jButton6.setBackground(new java.awt.Color(51, 255, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Yeni Oyun");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Skoru Kaydet");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel24.setText("Süre:");

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Skorlar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel28.setText("Tarih");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(23, 23, 23)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Oyun Alanı")));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soru:");

        jLabel4.setText("  -");

        jLabel5.setText(" - ");

        jLabel6.setText(" - ");

        jLabel7.setText("  -  ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Cevap:");

        jTextField2.setText(" ");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Cevapla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Harf Alayım");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton5.setText("Sıradaki Soru Gelsin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("SÜRE");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Ek Süre");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel22.setText("Süre:");

        jLabel23.setText("Cevaplama Süreniz:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));

        jLabel27.setText("Soru Değeri:");

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Joker");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addGap(13, 13, 13)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      jPanel1.setEnabled(false);
      jButton1.setVisible(false);
      jButton9.setVisible(false);
      jButton6.setVisible(false);
      jLabel26.setText(""+sorudegeri);
      durum=true;
      Thread t=new Thread()
      {
          public void run()
          {
              for(;;)
              {
                if (durum==true) 
                    {
                        try{
                            sleep(1);
                            if (salise>1000) {
                                salise=0;
                                saniye--;
                            }
                            if (saniye<0) {
                                salise=0;
                                saniye=59;
                                dakika--;
                            }
                            if (dakika==0&saniye==0)  
                            {
                                durum=false;
                                jButton5.setVisible(false);
                                soru="";
                                jLabel15.setText("Maalesef süreniz doldu!");
                                jLabel3.setText("");
                                jButton1.setVisible(false);
                                jButton2.setVisible(false);
                                jButton3.setVisible(false);
                                jButton4.setVisible(false);
                                jButton5.setVisible(false);
                                jButton6.setVisible(true);
                                jButton8.setVisible(true);
                                jButton12.setVisible(true);
                            }
                            salise++;
                            jLabel16.setText(dakika+":"+saniye);
                            
                            
                        }
                        
                        catch(Exception e)
                        {
                            
                        }
                    }
                else
                    {
                        break;
                    }
              }
          }
      };
      t.start();
        
    //    
    jButton2.setVisible(false);
    ad=jTextField1.getText();
    jTextField1.setEnabled(false);   
    jPanel2.setVisible(true);
    jPanel3.setVisible(true);
    jLabel3.setText(soru);
    jLabel21.setText(Integer.toString(skor));
    jLabel19.setText(ad);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (dakika==0&saniye==0) {
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel3.setText("Süre Doldu");
            
        }
        
        jButton4.setVisible(false);
        dogru=0;
        
        if (jTextField2.getText().toUpperCase().equals(cevap.toUpperCase())) {
            jLabel15.setText("Bildiniz!");
            jLabel15.setForeground(Color.blue);
            jButton5.setVisible(true);
            durum2=false;
            jButton2.setVisible(false);
            jButton7.setVisible(false);
            dogru++;
            if (sorusayac==0) {
                skor=400-(harfsayac*100);
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==1) {
                skor=(skor)+(400-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==2) {
                skor=skor+(500-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==3) {
                skor+=(500-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==4) {
                skor=skor+(600-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==5) {
                skor=skor+(600-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==6) {
                skor=skor+(700-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==7) {
                skor=skor+(700-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==8) {
                skor=skor+(800-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==9) {
                skor=skor+(800-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==10) {
                skor=skor+(900-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==11) {
                skor=skor+(900-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==12) {
                skor=skor+(1000-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            else if (sorusayac==13) {
                skor=skor+(1000-(harfsayac*100));
                jLabel21.setText(Integer.toString(skor));
            }
            
        }
        else{
            jLabel15.setText("YANLIŞ!");
            jLabel15.setForeground(Color.red);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
        jTextField2.setText("");
        
        if (jokersayar2<2) {
            jButton11.setVisible(true);
        }
        
        data=null;
    dataArray2 = null;
        rndsayac=-1;
        sorusayac++;
        harfsayac=0;
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jButton3.setVisible(true);
        jButton7.setVisible(false);
        jLabel15.setText("");
        durum=true;
        Thread t=new Thread()
      {
          public void run()
          {
              for(;;)
              {
                if (durum==true) 
                    {
                        try{
                            sleep(1);
                            if (salise>1000) {
                                salise=0;
                                saniye--;
                            }
                            if (saniye<0) {
                                salise=0;
                                saniye=59;
                                dakika--;
                            }
                            if (dakika==0&saniye==0) 
                            {
                                durum=false;
                                jButton5.setVisible(false);
                                soru="";
                                jLabel15.setText("Maalesef süreniz doldu!");
                                jLabel3.setText("");
                                jButton1.setVisible(false);
                                jButton2.setVisible(false);
                                jButton3.setVisible(false);
                                jButton4.setVisible(false);
                                jButton5.setVisible(false);
                                jButton6.setVisible(true);
                                jButton8.setVisible(true);
                                jButton12.setVisible(true);
                            }
                            salise++;
                            jLabel16.setText(dakika+":"+saniye);
                            
                        }
                        
                        catch(Exception e)
                        {
                            
                        }
                    }
                else
                    {
                        break;
                    }
              }
          }
      };
      t.start();  
      
        
        durum2=false;
        salise2=0;
        saniye2=20;
        jLabel17.setText("");
        jButton4.setVisible(true);
       
        if (sorusayac==1) {
        sorudegeri=400;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            
            list.clear();
        for (int x=0; x<4; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
               int rnd2= (int) (Math.random()*satirSayisi());
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*satirSayisi());
               }
            veri=new String[ss];
         try
        {
            FileInputStream fStream=new FileInputStream("4Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri[rnd2];
        dataArray=data.split("--");
        soru=dataArray[0];
        cevap=dataArray[1];
        jLabel3.setText(soru); 

        }
        
        
        if (sorusayac==2) {
        sorudegeri=500;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<5; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
             rnd= (int) ((Math.random()*ss2));
            veri2=new String[ss2];
         try
        {
            FileInputStream fStream=new FileInputStream("5Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri2[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri2[rnd];
        dataArray2=data.split("--");
        soru=dataArray2[0];
        cevap=dataArray2[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==3) {
        sorudegeri=500;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<5; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
            int rnd2= (int) (Math.random()*ss2);
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*ss2);
               }
            veri2=new String[ss2];
         try
        {
            FileInputStream fStream=new FileInputStream("5Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri2[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri2[rnd2];
        dataArray2=data.split("--");
        soru=dataArray2[0];
        cevap=dataArray2[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==4) {
        sorudegeri=600;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<6; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
             rnd= (int) ((Math.random()*ss3));
            veri3=new String[ss3];
         try
        {
            FileInputStream fStream=new FileInputStream("6Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri3[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        data=veri3[rnd];
        dataArray3=data.split("--");
        soru=dataArray3[0];
        cevap=dataArray3[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==5) {
        sorudegeri=600;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<6; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
            
            int rnd2= (int) (Math.random()*ss3);
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*ss3);
               }
            veri3=new String[ss3];
         try
        {
            FileInputStream fStream=new FileInputStream("6Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri3[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri3[rnd2];
        dataArray3=data.split("--");
        soru=dataArray3[0];
        cevap=dataArray3[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==6) {
        sorudegeri=700;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<7; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
            
            rnd= (int) ((Math.random()*ss4));
            veri4=new String[ss4];
         try
        {
            FileInputStream fStream=new FileInputStream("7Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri4[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        data=veri4[rnd];
        dataArray4=data.split("--");
        soru=dataArray4[0];
        cevap=dataArray4[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==7) {
        sorudegeri=700;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<7; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
            
            int rnd2= (int) (Math.random()*ss4);
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*ss4);
               }
            veri4=new String[ss4];
         try
        {
            FileInputStream fStream=new FileInputStream("7Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri4[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri4[rnd2];
        dataArray4=data.split("--");
        soru=dataArray4[0];
        cevap=dataArray4[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==8) {
        sorudegeri=800;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("  -  ");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<8; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
            
            rnd= (int) ((Math.random()*ss5));
            veri5=new String[ss5];
         try
        {
            FileInputStream fStream=new FileInputStream("8Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri5[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        data=veri5[rnd];
        dataArray5=data.split("--");
        soru=dataArray5[0];
        cevap=dataArray5[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==9) {
        sorudegeri=800;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("  -  ");
        jLabel12.setText("");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<8; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
 
            int rnd2= (int) (Math.random()*ss5);
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*ss5);
               }
            veri5=new String[ss5];
         try
        {
            FileInputStream fStream=new FileInputStream("8Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri5[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri5[rnd2];
        dataArray5=data.split("--");
        soru=dataArray5[0];
        cevap=dataArray5[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==10) {
        sorudegeri=900;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("  -  ");
        jLabel12.setText("  -  ");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<9; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
                   
            rnd= (int) ((Math.random()*ss6));
            veri6=new String[ss6];
         try
        {
            FileInputStream fStream=new FileInputStream("9Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri6[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        data=veri6[rnd];
        dataArray6=data.split("--");
        soru=dataArray6[0];
        cevap=dataArray6[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==11) {
        sorudegeri=900;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("  -  ");
        jLabel12.setText("  -  ");
        jLabel13.setText("");
            list.clear();
        for (int x=0; x<9; x++) {
            list.add(x);
        }
        Collections.shuffle(list);                    
            
            int rnd2= (int) (Math.random()*ss6);
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*ss6);
               }
            veri6=new String[ss6];
         try
        {
            FileInputStream fStream=new FileInputStream("9Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri6[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        data=veri6[rnd2];
        dataArray6=data.split("--");
        soru=dataArray6[0];
        cevap=dataArray6[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==12) {
        sorudegeri=1000;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("  -  ");
        jLabel12.setText("  -  ");
        jLabel13.setText("  -  ");
            list.clear();
        for (int x=0; x<10; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
                
            rnd= (int) ((Math.random()*ss7));
            veri7=new String[ss7];
         try
        {
            FileInputStream fStream=new FileInputStream("10Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri7[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        
        data=veri7[rnd];
        dataArray7=data.split("--");
        soru=dataArray7[0];
        cevap=dataArray7[1];
        jLabel3.setText(soru); 
        }
        
        if (sorusayac==13) {
        sorudegeri=1000;
        jLabel26.setText(""+sorudegeri);
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("  -  ");
        jLabel9.setText("  -  ");
        jLabel10.setText("  -  ");
        jLabel11.setText("  -  ");
        jLabel12.setText("  -  ");
        jLabel13.setText("  -  ");
            list.clear();
        for (int x=0; x<10; x++) {
            list.add(x);
        }
        Collections.shuffle(list);
     
            int rnd2= (int) (Math.random()*ss7);
               while(rnd2==rnd)
               {
                   rnd2= (int) (Math.random()*ss7);
               }
            veri7=new String[ss7];
         try
        {
            FileInputStream fStream=new FileInputStream("10Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri7[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }     

        data=veri7[rnd2];
        dataArray7=data.split("--");
        soru=dataArray7[0];
        cevap=dataArray7[1];
        jLabel3.setText(soru); 
        }
       
        if (sorusayac>=14) {
         soru="";
         jLabel3.setText("Tum Soruları Gordunuz Tebrikler!");
         jLabel25.setText(""+dakika+":"+saniye);
         jButton1.setVisible(false);
         jButton2.setVisible(false);
         jButton3.setVisible(false);
         jButton4.setVisible(false);
         jButton5.setVisible(false);
         jButton6.setVisible(true);
         durum=false;
         jButton8.setVisible(true);
         jButton12.setVisible(true);
         jButton11.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton11.setVisible(false);
        sorudegeri=sorudegeri-100;
        jLabel26.setText(""+sorudegeri);
        rndsayac++;
        harfsayac++;
      
    random=list.get(rndsayac);
                
                
        if (cevap.length()==harfsayac) {
            skor=skor-(100*harfsayac);
            jLabel21.setText(Integer.toString(skor));
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton5.setVisible(true);
            durum=false;
        }
        
        if (rndsayac==cevap.length()-1) {
            jButton4.setVisible(false);
        }
        String harf="";
        harf=cevap.substring((random), (random+1));
        
     
        if (random==0) {
            jLabel4.setText(harf);
        }
        else if (random==1) {
            jLabel5.setText(harf);
        }
        else if (random==2) {
            jLabel6.setText(harf);
        }
        else if (random==3) {
            jLabel7.setText(harf);
        }
        else if (random==4) {
            jLabel8.setText(harf);
        }
        else if (random==5) {
            jLabel9.setText(harf);
        }
        else if (random==6) {
            jLabel10.setText(harf);
        }
        else if (random==7) {
            jLabel11.setText(harf);
        }
        else if (random==8) {
            jLabel12.setText(harf);
        }
        else if (random==9) {
            jLabel13.setText(harf);
        }
        else if (random==10) {
            jLabel14.setText(harf);
        }
        if (harfsayac>cevap.length()) {
            jButton4.setVisible(false);
            jLabel15.setText("Tüm Harfleri Aldınız");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton5.setVisible(false);
        if (jokersayar>=2) {
            jButton7.setVisible(false);
        }
        else
        {
            jButton7.setVisible(true);
        }
        durum=false;
        jButton3.setVisible(false);
        
        //
        durum2=true;
      Thread t2=new Thread()
      {
          public void run()
          {
              for(;;)
              {
                if (durum2==true) 
                    {
                        try{
                            sleep(1);
                            if (salise2>1000) 
                            {
                                salise2=0;
                                saniye2--;
                            }
                           if (saniye2==0) 
                           {
                                durum2=false;
                                jButton2.setVisible(false);
                                jButton5.setVisible(true);
                                jTextField2.setText(cevap);
                                jButton7.setVisible(false);
                                jButton11.setVisible(false);
                                if (jLabel15.getText()!="Bildiniz!") {
                                   skor=skor-(100*cevap.length());
                                   jLabel21.setText(""+skor);
                               }
                           }
                            salise2++;
                            jLabel17.setText(""+saniye2);
                            
                        }
                        
                        catch(Exception e)
                        {
                            
                        }
                    }
                else
                    {
                        break;
                    }
              }
          }
      };
      t2.start();

       jButton4.setVisible(false);
       jButton2.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton1.setVisible(true);
        jButton9.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(true);
        jPanel1.setEnabled(true);
        jButton1.setVisible(true);
        cevap="";
        soru="";
        skor=0;
        ad="";
        jLabel25.setText("");
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
      dakika=4;saniye=0;salise=0;
      durum=true; 
      int rnd= (int) ((Math.random()*satirSayisi()));
      sorusayac=0;
      veri=new String[ss];
         try
        {
            FileInputStream fStream=new FileInputStream("4Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri[rnd];
        dataArray=data.split("--");
        soru=dataArray[0];
        cevap=dataArray[1];

        //
        list.clear();
        for (int i=0; i<4; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);
        
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jokersayar++;
        if (jokersayar>2) {
            jButton7.setVisible(false);
        }
        else
        {
            saniye2=20;
            if (jokersayar==2) {
                jButton7.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       File f=new File("skorlar.txt");
       try
       {
           BufferedWriter yaz=new BufferedWriter(new OutputStreamWriter(new FileOutputStream(f,true)));
           yaz.write(""+skor+"--"+ad.toString());
           yaz.newLine();
           yaz.flush();
           yaz.close();
           
       }
       catch(IOException e){
           
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        soruEkle ekran2=new soruEkle();
        ekran2.show();
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        JOptionPane.showMessageDialog(null,"-Ek süre hakkınızı cevaplama 20 saniyeyi yeniler\n-Joker ile harf almadan bilirseniz puanınız 2 katına çıkar\nHER JOKER 2 KEZ KULLANILABİLİR!");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jokersayar2++;
        harfsayac=-1*(cevap.length());
        jButton4.setVisible(false);  
        jButton11.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       oyuncuBilgileri ekran3=new oyuncuBilgileri();
        ekran3.show();
        dispose();
        
        jButton1.setVisible(true);
        jButton9.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(true);
        jPanel1.setEnabled(true);
        jButton1.setVisible(true);
        cevap="";
        soru="";
        skor=0;
        ad="";
        jLabel25.setText("");
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
      dakika=4;saniye=0;salise=0;
      durum=true; 
      int rnd= (int) ((Math.random()*satirSayisi()));
      sorusayac=0;
      veri=new String[ss];
         try
        {
            FileInputStream fStream=new FileInputStream("4Harfliler.txt");
            DataInputStream dStream=new DataInputStream(fStream);
            BufferedReader bReader=new BufferedReader(new InputStreamReader(dStream));
            
            int i=0;
            while((str=bReader.readLine())!=null){
                veri[i]=str;
                i++;
            }
            dStream.close();
        }
        catch(Exception e)
        {
            System.err.println("Hata : "+e.getMessage());
        }
        

        data=veri[rnd];
        dataArray=data.split("--");
        soru=dataArray[0];
        cevap=dataArray[1];

        //
        list.clear();
        for (int i=0; i<4; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);
        
        jLabel4.setText("  -  ");
        jLabel5.setText("  -  ");
        jLabel6.setText("  -  ");
        jLabel7.setText("  -  ");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kelime_oyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kelime_oyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kelime_oyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kelime_oyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kelime_oyunu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
